services:
  - type: web
    name: e-shop-server
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
